import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-flair-dark/90 backdrop-blur-sm border-t border-white/10 py-4">
      <div className="w-full px-4 sm:px-6 md:px-8 text-center">
        <p className="text-xs text-text-muted">
          <strong>Disclaimer:</strong> This dashboard is for internal informational purposes only. Status information is generated by API polling and may not always be 100% accurate or up-to-the-minute. Please verify critical incidents through official service status pages.
        </p>
      </div>
    </footer>
  );
};

export default Footer;